version: '3'

services:
  kong-database:
    image: postgres:latest
    container_name: kong-database
    user: root
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    user: root
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    restart: on-failure

  kong:
    image: kong:latest
    container_name: kong
    user: root
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ADMIN_GUI_URL: 'http://192.168.88.53:5002/'
    ports:
      - "5000:8000"   # Proxy
      - "5443:8443"   # Proxy SSL
      - "8001:8001"   # Admin API
      - "5002:8002"   # Admin API
    depends_on:
      - kong-migrations
    restart: always

 